apiVersion: apps/v1
kind: Deployment
metadata:
  name: drf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drf-app
  template:
    metadata:
      labels:
        app: drf-app
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done;']
      containers:
        - name: drf-app
          image: olehlohvyn2003/my-drf-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: app_db
            - name: DB_USER
              value: app_user
            - name: DB_PASSWORD
              value: secure_password
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
