apiVersion: apps/v1
kind: Deployment
metadata:
  name: drf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drf-app
  template:
    metadata:
      labels:
        app: drf-app
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done;']
      containers:
        - name: drf-app
          image: olehlohvyn2003/my-drf-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: db-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: db-secret
