apiVersion: apps/v1
kind: Deployment
metadata:
  name: drf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drf-app
  template:
    metadata:
      labels:
        app: drf-app
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command: ['sh', '-c', 'until pg_isready -h postgres -p 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done;']
      containers:
        - name: testify-users
          image: olehlohvyn2003/testify-users:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
